name: Reusable Azure Login Workflow

# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest
    outputs:
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Verify Login
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account show;
            az resources list --resource-group hisham-rg
