name: Reusable Azure Login Workflow

# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest
    env:
        RESOURCE_GROUP: hisham-rg
    outputs:
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Verify Login, List Resources
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account show;
            az resource list --resource-group $RESOURCE_GROUP --output table

      - name: Verify Terraform Remote Backend Storage Account
        run: |
          echo "Checking if Terraform State storage account exists..."
          if az storage account show --name tfstatestorage131025 --resource-group hisham-rg --output table; then
            echo "✅ tfstate Storage account found."
          else
            echo "❌ Storage account 'tfstatestorage131025' not found."
          fi
      - name: Terraform State list
        run: terraform state list 
