name: Provision Resources
on: 
    push:
    workflow_dispatch:
        inputs:
            plan_only:
                description: "Only plan the Terraform Apply step (true/false)"
                required: false
                default: "false"
            trigger_destroy:
                description: "Trigger destroy workflow after creation (true/false)"
                required: false
                default: "true"   


permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
jobs:
    call-login:
      uses: ./.github/workflows/azure-login.yaml
      secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    create-storage:
      needs: call-login
      runs-on: ubuntu-latest
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        STORAGE_ACC_NAME: ${{ vars.STORAGE_ACCOUNT }}
        RESOURCE_GROUP: hisham-rg

      steps:

          - name: "Checkout Code"
            uses: actions/checkout@v4

          - name: "Setup Terraform"
            uses: hashicorp/setup-terraform@v3

          - name: Terraform Init
            run: terraform init -reconfigure -upgrade

          - name: Terraform State list
            run: terraform state list 

          - name: Create terraform.tfvars file dynamically
            run: |
              cat > terraform.tfvars <<EOF
              storage_acc_name   = "${{ vars.STORAGE_ACCOUNT }}"
              subscription_id    = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
              tenant_id          = "${{ secrets.AZURE_TENANT_ID }}"
              client_id          = "${{ secrets.AZURE_CLIENT_ID }}"
              resource_group     = "hisham-rg"
              EOF

          - name: Terraform Plan
            run: terraform plan -out storageaccount.tfplan -var-file=terraform.tfvars

          - name: Make Markdown Summary with terraform-j2md
            id: plan-summary
            run: | 
              terraform show -json storageaccount.tfplan | utils/terraform-j2md > storageaccplan.md
              cat storageaccplan.md >> $GITHUB_STEP_SUMMARY

          - name: Terraform Apply - Create Storage Account
            # if: ${{ github.event.inputs.plan_only == 'false' }}
            run: terraform apply -auto-approve -var-file=terraform.tfvars

          # - name: Trigger Destroy Workflow 
          #   if: ${{ github.event.inputs.trigger_destroy == 'true' }}
          #   env:
          #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #   run: |
          #     echo "Triggering Destroy Workflow..."
          #     gh workflow run "Destroy Azure Storage Account with Terraform" --ref main
