name: Create Azure Storage Account with Terraform
on: [push, workflow_dispatch]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
jobs:
    call-login:
      uses: ./.github/workflows/azure-login.yaml
      secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    create-storage:
      needs: call-login
      runs-on: ubuntu-latest
      steps:
          - name: "Checkout Code"
            uses: actions/checkout@v4

          - name: "Setup Terraform"
            uses: hashicorp/setup-terraform@v3

          - name: Terraform Init
            run: terraform init
            
          - name: Terraform Apply - Create Storage Acc
            run: terraform apply -auto-approve 
              -var "storage_acc_name=${{ vars.STORAGE_ACCOUNT }}" 
              -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
              -var "client_id=${{ secrets.AZURE_CLIENT_ID }}"
              -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
