name: Destroy Azure Storage Account with Terraform
on:
    workflow_dispatch: 
    workflow_run:
      workflows: ["Create Azure Storage Account with Terraform"]
      types: completed

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
jobs:
    call-login:
      uses: ./.github/workflows/azure-login.yaml
      secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    destroy-storage:
      needs: call-login
      runs-on: ubuntu-latest
      steps:
          - name: "Wait before Destroying"
            run: sleep 60 # Wait for a minute
    
          - name: "Checkout Code"
            uses: actions/checkout@v4

          - name: "Setup Terraform"
            uses: hashicorp/setup-terraform@v3

          - name: Terraform Init
            run: terraform init

          - name: Check if Storage Account already Exists
            id: check
            uses: azure/cli@v2
            with:
              inlineScript: |
                echo "Checking if Storage Account $STORAGE_ACC_NAME exists"
                if az storage account show -n $STORAGE_ACC_NAME -g $RESOURCE_GROUP >/dev/null 2>&1; then
                  echo "exists=true" >> $GITHUB_OUTPUT
                else
                  echo "exists=false" >> $GITHUB_OUTPUT
                fi
            
          - name: Import Existing Storage Account into Terraform State
            if: steps.check.outputs.exists == 'true'
            run: |
              echo "Importing storage account into Terraform state"
              terraform import azurerm_storage_account.githubactionsstorage /subscriptions/$ARM_SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$STORAGE_ACC_NAME

          - name: Terraform Plan - Destroy
            run: terraform plan -destroy
              -var "storage_acc_name=${{ vars.STORAGE_ACCOUNT }}" 
              -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
              -var "client_id=${{ secrets.AZURE_CLIENT_ID }}"
              -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
            
          - name: Terraform Destroy Storage Account
            run: terraform destroy -auto-approve 
              -var "storage_acc_name=${{ vars.STORAGE_ACCOUNT }}" 
              -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
              -var "client_id=${{ secrets.AZURE_CLIENT_ID }}"
              -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
