name: Destroy Resources
on:
    workflow_dispatch:
    workflow_run:
      workflows: ["Provision Resources"]
      types: completed

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
jobs:
    call-login:
      uses: ./.github/workflows/azure-login.yaml
      secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    destroy-storage:
      needs: call-login
      environment: development
      runs-on: ubuntu-latest
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        STORAGE_ACC_NAME: ${{ vars.STORAGE_ACCOUNT }}
        RESOURCE_GROUP: hisham-rg
        TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_storage_acc_name: ${{ vars.STORAGE_ACCOUNT }}

      steps:
          - name: "Checkout Code"
            uses: actions/checkout@v4

          - name: "Setup Terraform"
            uses: hashicorp/setup-terraform@v3

          - name: Terraform Init - Remote Backend
            run: terraform init -reconfigure -upgrade

          - name: Terraform State list
            run: terraform state list

          - name: Create terraform.tfvars file dynamically
            run: |
              cat > terraform.tfvars <<EOF
              storage_acc_name   = "${{ vars.STORAGE_ACCOUNT }}"
              subscription_id    = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
              tenant_id          = "${{ secrets.AZURE_TENANT_ID }}"
              client_id          = "${{ secrets.AZURE_CLIENT_ID }}"
              resource_group     = "hisham-rg"
              EOF

          - name: Terraform Plan ( Destroy )
            run: terraform plan -destroy -out storageaccountdestroy.tfplan -var-file=terraform.tfvars

          - name: Make Markdown Summary with terraform-j2md
            id: plan-summary
            run: | 
              terraform show -json storageaccountdestroy.tfplan | utils/terraform-j2md > storageaccplan.md
              cat storageaccplan.md >> $GITHUB_STEP_SUMMARY
            
          - name: Terraform Destroy Storage Account
            run: terraform destroy -auto-approve -var-file=terraform.tfvars
